version: '2'
services:
    web:
        build: .
        user: app
        working_dir: /home/app/src
        ports:
            - '8000:8000'
        volumes:
            - .:/home/app/src
        command: 'bin/console server:run 0.0.0.0:8000'
