security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(css|images|js)/
            security: false

        main:
            anonymous: ~
